config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/register'
  post '/sessions' => 'sessions#create'
  post '/users/create' => 'users#create'
  get '/' => 'product#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :product, only: [:index, :show]
  resources :cart_items
  resources :searches
  resource :carts, only: [:show]

  root to: 'product#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/administrator.rb
class Administrator < ApplicationRecord
	validates :username, :password, presence: true
	validates :username, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :shopping_cart
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
  	if persisted?
  		self[:unit_price]
  	else
  		product.price
  	end
  end

  def total_price
  	unit_price * quantity
  end

  private
  	def set_unit_price
  		self[:unit_price] = unit_price
  	end

  	def set_total_price
  		self[:total_price] = quantity * set_unit_price
  	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_categories
	has_many :products, through: :product_categories
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :cart_item
	has_many :product_categories
	has_many :categories, through: :product_categories

	accepts_nested_attributes_for :product_categories, allow_destroy: true

	def self.search(search)
		if search
			where(["name LIKE ?", "%#{search}%"])
		else
			all
		end
		
	end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
	def search_products
		
		products = Product.all
		categories = Category.all

		categ_ar = categories.where(["name LIKE ?","%#{category}%"]) if category.present?
		categ_id = categ_ar.ids if category.present?
		categ = Category.find(categ_id[0]) if category.present?
		products = categ.products if category.present?

		products = products.where(["name LIKE ?","%#{keywords}%"]) if keywords.present?		
		products = products.where(["price >= ?", min_price]) if min_price.present?
		products = products.where(["price <= ?", max_price]) if max_price.present?

		return products
	end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  has_many :cart_item
  before_save :set_subtotal

  def subtotal
  	cart_item.collect { |item| item.valid? ? (item.unit_price*item.quantity) : 0}.sum
  end

  private
  	def set_subtotal
  		self[:subtotal] = subtotal
  	end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@cart_items = current_order.cart_item
	end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
  	@product_collection = Product.order(:name).page(params[:page]).per(6).search(params[:search])
  	@item = current_order.cart_item.new
  end

  def show
  	@product = Product.find(params[:id])
  	@item = current_order.cart_item.new
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	def new
		@search = Search.new
		@categories = Category.all.pluck(:name)

		
	end

	def create
		@search = Search.create(search_params)
		redirect_to @search
	end

	def show
		@search = Search.find(params[:id])
		@item = current_order.cart_item.new
	end

	private

	def search_params
		params.require(:search).permit(:keywords, :category, :min_price, :max_price)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.find_by(username:login_params[:username])		

		if user && user.password_digest == login_params[:password_digest]
			session[:user_id] = user.id
			redirect_to '/'
		else
			flash[:login_errors] = "Invalid Login"
			redirect_to '/users/index'
		end
	end

		private
			def login_params
				params.require(:login).permit(:username, :password_digest)
			end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		
	end

	def create
		user = User.new(user_params)

		if user.save
			session[:user_id] = user.id
			flash[:success] = "Registration Successful!"
			redirect_to '/users/register'
		else
			flash[:register_errors] = user.errors.full_messages
			redirect_to '/users/register'
		end
	end

		private
			def user_params
				params.require(:user).permit(:name, :username, :password_digest)
			end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_order
		if !session[:shopping_cart_id].nil?
			ShoppingCart.find(session[:shopping_cart_id])
		else
			ShoppingCart.new
		end
	end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product/_product.html.erb
<div class="container col-md-12 col-lg-4 border shadow-sm p-3 bg-light rounded m-0 mt-2 mb-2 mx-auto">
	<p>
		<b>Name: </b> <%= link_to product.name, product %>
	</p>
	<% if product.image.present? %>
		<p>
			<%= image_tag product.image.url, :size => "300x300" %>
		</p>
	<% end %>
	<%= form_for(@item, remote: true) do |f| %>
		<%= f.hidden_field :product_id, value: product.id %>
		<h5><%= product.price %></h5>
		<div class="form-group">
			<%= f.hidden_field :quantity, value: 1, min: 1, class: 'form-control' %>
		</div>
		<%= f.submit "Add to cart", class: 'btn btn-primary btm-sm' %>
	<% end %>
</div>

app/views/product/index.html.erb
<div class="container">
  <%= form_tag product_index_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
  <% end %>

  <%= link_to "Advanced Search", new_search_path %>
</div>
<div class="row">
	<div class="container">
		<div class="row">
			<%= render partial: 'product',
		   collection: @product_collection %>
		</div>
	</div>	
</div>

app/views/product/show.html.erb
<%= render partial: 'product',
		   object: @product %>

<%= link_to 'Products', root_path %>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_for @search, html: {class: "pure-form"} do |s| %>
	<div class="form-group">
		<%= s.label :keywords %><br/>
		<%= s.text_field :keywords, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= s.label :category %><br/>
		<%= s.select :category, options_for_select(@categories), :include_blank => true, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= s.label :min_price, "Min Price" %> 
		<%= s.text_field :min_price, size: 10, class: "form-control" %>
		<%= s.label :min_price, "Max Price" %> 
		<%= s.text_field :max_price, size: 10, class: "form-control" %>
	</div>

	<div class="actions mb-2 mt-2"><%= s.submit "Search", class: "pure-button pure-button-primary" %></div>

<% end %>

<%= link_to 'Back', product_index_path %>

app/views/searches/show.html.erb

	<h1>Search Result</h1>
	<p><%= link_to 'Back', new_search_path %></p>

	<% if @search.search_products.nil? %>
		<p>No Records Found</p>
	<% else %>
	<div class="row">
		<div class="container">
		<div class="row">		
		<% @search.search_products.each do |c| %>
		<div class="container col-md-12 col-lg-4 border shadow-sm p-3 bg-light rounded m-0 mt-2 mb-2 mx-auto">
			<p>
			<b>Name: </b> <%= c.name %>
			</p>
			<% if c.image.present? %>
				<p>
					<%= image_tag c.image.url, :size => "300x300" %>
				</p>
			<% end %>
			<%= form_for(@item, remote: true) do |f| %>
				<%= f.hidden_field :product_id, value: c.id %>
				<h5><%= c.price %></h5>
				<div class="form-group">
					<%= f.hidden_field :quantity, value: 1, min: 1, class: 'form-control' %>
				</div>
				<%= f.submit "Add to cart", class: 'btn btn-primary btm-sm' %>
			<% end %>
			
		</div>
		<% end %>
		</div>
		</div>
	</div>		
	<% end %>	

app/views/users/index.html.erb
<h1>Login</h1>

<form action="/sessions" method="POST">
	<div class="form-group">
		<% if flash[:login_errors] %>
    		<div class="alert alert-danger" role="alert"><%= flash[:login_errors] %></div>
	    <% end %>
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<label for="exampleInputEmail1">Email address</label>
		<input class="form-control" type="email" name="login[username]" placeholder="email">
		<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
	</div>
	<div class="form-group">
		<label for="exampleInputPassword1">Password</label>
		<input class="form-control" type="password" name="login[password_digest]" placeholder="password">		
	</div>
	<button type="submit" class="btn btn-primary">Submit</button>	
</form>
<div class="mt-2">
	<%= link_to "Not yet registered? Click Here!", users_register_path %>
</div>

app/views/users/register.html.erb
<h1>Registration</h1>

<form action="/users/create" method="POST">
	<% if flash[:success] %>
		<div class="alert alert-danger" role="alert"><%= flash[:success] %></div>
    <% end %>
	<div class="form-group">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<label for="name">Name</label>
		<input class="form-control" type="name" name="user[name]" placeholder="name">
	</div>
	<div class="form-group">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<label for="username">Email</label>
		<input class="form-control" type="email" name="login[username]" placeholder="email">
	</div>
	<div class="form-group">
		<label for="password">Password</label>
		<input class="form-control" type="password" name="user[password_digest]" placeholder="password">	
	</div>
	<button type="submit" class="btn btn-primary">Submit</button>	
</form>
<div class="mt-2">
	<%= link_to "Already registered? Click HERE!", users_index_path %>
</div>