config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/register'
  post '/sessions' => 'sessions#create'
  post '/users/create' => 'users#create'
  get '/' => 'product#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :product, only: [:index, :show]
  resources :cart_items
  resources :searches
  resource :carts, only: [:show]

  root to: 'product#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/administrator.rb
class Administrator < ApplicationRecord
	validates :username, :password, presence: true
	validates :username, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :shopping_cart
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
  	if persisted?
  		self[:unit_price]
  	else
  		product.price
  	end
  end

  def total_price
  	unit_price * quantity
  end

  private
  	def set_unit_price
  		self[:unit_price] = unit_price
  	end

  	def set_total_price
  		self[:total_price] = quantity * set_unit_price
  	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product_categories
	has_many :products, through: :product_categories
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :cart_item
	has_many :product_categories
	has_many :categories, through: :product_categories

	accepts_nested_attributes_for :product_categories, allow_destroy: true

	def self.search(search)
		if search
			where(["name LIKE ?", "%#{search}%"])
		else
			all
		end
		
	end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
	def search_products
		
		products = Product.all
		categories = Category.all

		categ_ar = categories.where(["name LIKE ?","%#{category}%"]) if category.present?
		categ_id = categ_ar.ids if category.present?
		categ = Category.find(categ_id[0]) if category.present?
		products = categ.products if category.present?

		products = products.where(["name LIKE ?","%#{keywords}%"]) if keywords.present?		
		products = products.where(["price >= ?", min_price]) if min_price.present?
		products = products.where(["price <= ?", max_price]) if max_price.present?

		return products
	end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  has_many :cart_item
  before_save :set_subtotal

  def subtotal
  	cart_item.collect { |item| item.valid? ? (item.unit_price*item.quantity) : 0}.sum
  end

  private
  	def set_subtotal
  		self[:subtotal] = subtotal
  	end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@cart_items = current_order.cart_item
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		
	end

	def create
		user = User.new(user_params)

		if user.save
			session[:user_id] = user.id
			flash[:success] = "Registration Successful!"
			redirect_to '/users/register'
		else
			flash[:register_errors] = user.errors.full_messages
			redirect_to '/users/register'
		end
	end

		private
			def user_params
				params.require(:user).permit(:name, :username, :password_digest)
			end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_order
		if !session[:shopping_cart_id].nil?
			ShoppingCart.find(session[:shopping_cart_id])
		else
			ShoppingCart.new
		end
	end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cart.html.erb
<%= link_to "#{current_order.cart_item.size} items in cart and price #{current_order.subtotal}", carts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamehub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>   
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
      <%= link_to "GameHUB", root_path, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item active cart">
            <%= render 'layouts/cart', :class => "text-primary" %>
          </li>
        </ul>

        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>    

    <div class="container col-md-12 col-lg-10 border shadow-sm p-4 mt-3 bg-light">
      <%= yield %>
    </div>

  </body>
</html>